#!/usr/bin/env python3
"""Embed the Windows scripts, preserving skfiy's single-binary distribution."""
from pathlib import Path
root = Path(__file__).resolve().parent.parent
parts = ['// Generated by scripts/embed_remote.py; edit remote-windows/*.ps1.\n', 'enum RemoteDesktopScripts {\n']
for name in ('worker', 'transport'):
    source = (root / 'remote-windows' / (name + '.ps1')).read_text()
    assert '"""#' not in source
    parts.append(f'    static let {name} = #"""\n{source}\n"""#\n')
parts.append('}\n')
(root / 'Sources/SkfiyKit/RemoteDesktopScripts.swift').write_text(''.join(parts))
