#!/bin/bash
# Regenerates Sources/SkfiyKit/EmbeddedExtension.swift from browser-extension/,
# so a single skfiy binary can install the extension without the repository
# (`skfiy setup`). Run it (or `make embed-extension`) after changing the
# extension; `make test` fails while the two differ. Reminds you when the
# extension changed but its version did not: skfiy doctor and setup compare
# versions to tell users to reload it in chrome://extensions.
set -euo pipefail
cd "$(dirname "$0")/.."
out=Sources/SkfiyKit/EmbeddedExtension.swift
version=$(sed -n 's/.*"version": *"\([^"]*\)".*/\1/p' browser-extension/manifest.json | head -1)
tmp=$(mktemp)
{
    echo "// Generated by scripts/embed_extension.sh from browser-extension/; do not edit."
    echo "// \`make embed-extension\` regenerates it, and a unit test checks that it matches."
    echo "// browser-extension version $version"
    echo ""
    echo "enum EmbeddedExtension {"
    echo "    /// File name and base64 content of every file in browser-extension/."
    echo "    static let files: [(name: String, base64: String)] = ["
    for file in browser-extension/*; do
        [ -f "$file" ] || continue
        echo "        (\"$(basename "$file")\", \"\"\""
        base64 -b 120 -i "$file" | sed 's/^/        /'
        echo "        \"\"\"),"
    done
    echo "    ]"
    echo "}"
} > "$tmp"
if cmp -s "$tmp" "$out"; then rm -f "$tmp"; exit 0; fi
previous=$(sed -n 's|^// browser-extension version ||p' "$out" 2>/dev/null | head -1)
mv "$tmp" "$out"
echo "Wrote $out"
if [ "$previous" = "$version" ]; then
    echo "Reminder: browser-extension/ changed but its version is still $version. Bump \"version\" in" \
         "browser-extension/manifest.json, or users already running it are not told to reload it." >&2
fi
