#!/bin/bash
# Regenerates Sources/SkfiyKit/EmbeddedExtension.swift from browser-extension/,
# so a single skfiy binary can install the extension without the repository
# (`skfiy setup`). Run it (or `make embed-extension`) after changing the
# extension; `make test` fails while the two differ.
set -euo pipefail
cd "$(dirname "$0")/.."
out=Sources/SkfiyKit/EmbeddedExtension.swift
tmp=$(mktemp)
{
    echo "// Generated by scripts/embed_extension.sh from browser-extension/; do not edit."
    echo "// \`make embed-extension\` regenerates it, and a unit test checks that it matches."
    echo ""
    echo "enum EmbeddedExtension {"
    echo "    /// File name and base64 content of every file in browser-extension/."
    echo "    static let files: [(name: String, base64: String)] = ["
    for file in browser-extension/*; do
        [ -f "$file" ] || continue
        echo "        (\"$(basename "$file")\", \"\"\""
        base64 -b 120 -i "$file" | sed 's/^/        /'
        echo "        \"\"\"),"
    done
    echo "    ]"
    echo "}"
} > "$tmp"
if cmp -s "$tmp" "$out"; then rm -f "$tmp"; else mv "$tmp" "$out"; echo "Wrote $out"; fi
